import jwt from 'jsonwebtoken'

// This file is only for development/testing purposes
// In production, tokens would be generated by an authentication service

const generateToken = (
    userId: string = '12345',
    workspaceId: string | number = '1',
    scopes: string[] = ['plans:read', 'plans:write', 'plans:delete', 'admin:access']
) => {
    const jwtSecret = process.env.JWT_SECRET || 'development-secret-key';
    
    const payload = {
        sub: userId,
        workspace_id: workspaceId,
        scopes: scopes,
        iat: Math.floor(Date.now() / 1000),
        exp: Math.floor(Date.now() / 1000) + (60 * 60) // 1 hour expiration
    };
    
    return jwt.sign(payload, jwtSecret);
};

// Example: Generate a token with read-only access
const readOnlyToken = generateToken('12345', '1', ['plans:read']);
console.log('Read-only token:', readOnlyToken);

// Example: Generate a token with read and write access
const readWriteToken = generateToken('12345', '1', ['plans:read', 'plans:write']);
console.log('Read-write token:', readWriteToken);

// Example: Generate a token with full access
const fullAccessToken = generateToken('12345', '207732', ['admin:access', 'plans:read', 'plans:write', 'plans:delete']);
console.log('Full access token:', fullAccessToken);

// Example: Generate a token for workspace 2
const workspace2Token = generateToken('12345', '2', ['plans:read', 'plans:write', 'plans:delete']);
console.log('Workspace 2 token:', workspace2Token);

// **** Tokens for admin API testing **** //

// Token with retailer_admin role - used for /admin/checkin
const retailerAdminToken = generateToken('12345', '1', ['retailer_admin']);
console.log('\nRetailer Admin token (for /admin/checkin):', retailerAdminToken);

// Token with admin:access role - used for /admin/audit-logs
const adminAccessToken = generateToken('12345', '1', ['admin:access']);
console.log('Admin Access token (for /admin/audit-logs):', adminAccessToken);

// Token with both retailer_admin and admin:access roles - for testing both admin APIs
const combinedAdminToken = generateToken('12345', '1', ['retailer_admin', 'admin:access']);
console.log('Combined Admin token (for all admin APIs):', combinedAdminToken);

