name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npm run type-check
      
      - name: Debug directory structure
        run: find . -name "*.test.ts" -type f
      
      - name: Run tests
        run: npm test
  
  deploy:
    name: Deploy to Encore Cloud
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    env:
      ENCORE_AUTH: ${{ secrets.ENCORE_AUTH_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install Encore CLI
        run: |
          curl -s https://encore.dev/install.sh | bash
          echo "$HOME/.encore/bin" >> $GITHUB_PATH
      
      - name: Set up Git for Encore
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Setup Encore auth
        run: |
          # Tạo thư mục cấu hình cho Encore
          mkdir -p ~/.encore
          
          # Xóa các file cấu hình cũ nếu có
          rm -f ~/.encore/authtoken ~/.encore/config.json 2>/dev/null || true
          
          # Tạo file cấu hình mới theo đúng định dạng
          cat > ~/.encore/config.json << EOF
          {
            "auth": {
              "active_token": "${{ secrets.ENCORE_AUTH_TOKEN }}",
              "tokens": ["${{ secrets.ENCORE_AUTH_TOKEN }}"]
            }
          }
          EOF
          chmod 600 ~/.encore/config.json
          
          # Kiểm tra file cấu hình
          echo "Kiểm tra file cấu hình Encore:"
          ls -la ~/.encore/
          
          # Thử xác thực với Encore
          echo "Thực hiện đăng nhập Encore..."
          encore auth login --auth-key=${{ secrets.ENCORE_AUTH_TOKEN }}
      
      - name: Deploy to Encore Cloud manually
        run: |
          # Hiển thị phiên bản Encore
          encore version
          
          # Kiểm tra trạng thái đăng nhập
          echo "Kiểm tra trạng thái đăng nhập:"
          encore auth status || true
          
          # Lấy app ID từ file encore.app
          APP_ID=$(cat encore.app | grep id | cut -d'"' -f4)
          echo "App ID: $APP_ID"
          
          # Bỏ qua bước link app và tạo remote thủ công
          echo "Tạo thư mục deploy tạm thời..."
          mkdir -p /tmp/encore-deploy
          cd /tmp/encore-deploy
          
          # Clone repo hiện tại
          echo "Clone repository để triển khai..."
          git clone $GITHUB_WORKSPACE .
          
          # Thiết lập thông tin git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Thiết lập deploy thông qua git
          echo "Cấu hình Git remote cho Encore..."
          git remote add encore "encore://$APP_ID.git"
          
          # Cấu hình SSH 
          echo "Cấu hình SSH cho Encore..."
          mkdir -p ~/.ssh
          ssh-keyscan encore.dev >> ~/.ssh/known_hosts 2>/dev/null || true
          ssh-keyscan git.encore.dev >> ~/.ssh/known_hosts 2>/dev/null || true
          
          # Thiết lập SSH options
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          
          # Thiết lập Git environment và credential
          export GIT_TRACE=1
          export GIT_CURL_VERBOSE=1
          export GIT_SSH_COMMAND="ssh -v -o StrictHostKeyChecking=no"
          
          # Thiết lập Git credentials
          git config --global credential.helper store
          echo "https://token:${{ secrets.ENCORE_AUTH_TOKEN }}@git.encore.dev" > ~/.git-credentials
          chmod 600 ~/.git-credentials
          
          # Đẩy code lên Encore
          echo "Đang triển khai lên Encore Cloud..."
          git push -v encore HEAD:refs/heads/main -f
          
          echo "===== Triển khai hoàn tất ====="
          echo "Kiểm tra trạng thái triển khai tại: https://app.encore.cloud/$APP_ID"