name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npm run type-check
      
      - name: Debug directory structure
        run: find . -name "*.test.ts" -type f
      
      - name: Run tests
        run: npm test
  
  deploy:
    name: Deploy to Encore Cloud
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Encore CLI
        run: |
          curl -s https://encore.dev/install.sh | bash
          echo "$HOME/.encore/bin" >> $GITHUB_PATH
      
      - name: Deploy to Encore Cloud
        run: |
          # Đăng nhập với API key
          encore auth login --auth-key=${{ secrets.ENCORE_AUTH_TOKEN }}
          
          # Hiển thị phiên bản Encore để debug
          encore version
          
          # Sử dụng lệnh deploy thay vì run
          # Tạo một tệp tin setup.sh để triển khai
          cat > setup.sh << 'EOF'
          #!/bin/bash
          set -e
          # Đặt các biến môi trường cần thiết
          export ENCORE_APP_ID="mission-brief-ec62"
          
          # Sử dụng curl để gửi yêu cầu API triển khai
          curl -X POST "https://api.encore.dev/v1/apps/${ENCORE_APP_ID}/deploy" \
            -H "Authorization: Bearer $ENCORE_AUTH_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "source": "github",
              "branch": "main",
              "commit": "'$(git rev-parse HEAD)'"
            }'
          
          echo "Đã gửi yêu cầu triển khai. Kiểm tra trạng thái tại https://app.encore.cloud/${ENCORE_APP_ID}"
          EOF
          
          # Thực thi script
          chmod +x setup.sh
          ./setup.sh
        env:
          ENCORE_AUTH_TOKEN: ${{ secrets.ENCORE_AUTH_TOKEN }}