name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npm run type-check
      
      - name: Debug directory structure
        run: find . -name "*.test.ts" -type f
      
      - name: Run tests
        run: npm test
  
  deploy:
    name: Deploy to Encore Cloud
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Deploy to Encore Cloud
        env:
          ENCORE_AUTH_TOKEN: ${{ secrets.ENCORE_AUTH_TOKEN }}
        run: |
          # Thêm comment này để trigger GitHub Actions - $(date)
          
          # Báo cáo thông tin môi trường
          echo "=== Thông tin môi trường ==="
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "Git version: $(git --version)"
          
          # Cài đặt Encore CLI
          echo "=== Cài đặt Encore CLI ==="
          curl -s https://encore.dev/install.sh | bash
          export PATH="$HOME/.encore/bin:$PATH"
          
          # Hiển thị phiên bản Encore
          echo "Encore version: $(encore version)"
          
          # Lấy thông tin app ID
          APP_ID=$(cat encore.app | grep id | cut -d'"' -f4)
          echo "App ID: $APP_ID"
          
          # === PHƯƠNG PHÁP 1: Sử dụng Encore deploy ===
          echo "=== Thử triển khai với Encore CLI ==="
          
          # Xác thực với Encore (tùy chọn -y)
          echo "$ENCORE_AUTH_TOKEN" | encore auth login --auth-key=- || echo "Xác thực không thành công, tiếp tục với phương pháp thay thế"
          
          # === PHƯƠNG PHÁP 2: Sử dụng Git Push ===
          echo "=== Triển khai với Git Push ==="
          
          # Tạo thư mục triển khai
          DEPLOY_DIR=$(mktemp -d)
          echo "Tạo thư mục triển khai tạm thời: $DEPLOY_DIR"
          
          # Sao chép repository vào thư mục triển khai
          cp -r . $DEPLOY_DIR
          cd $DEPLOY_DIR
          
          # Thiết lập Git
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy to Encore Cloud from GitHub Actions"
          
          # Thiết lập SSH cho Encore
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          
          # Tạo đường dẫn đến Git remote
          ENCORE_REMOTE="encore://$APP_ID.git"
          echo "Encore remote: $ENCORE_REMOTE"
          
          # Thiết lập biến môi trường xác thực
          export ENCORE_AUTH="$ENCORE_AUTH_TOKEN"
          
          # Thêm remote và đẩy code
          git remote add encore $ENCORE_REMOTE
          GIT_TRACE=1 git push -f encore main || echo "Không thể đẩy code lên Encore, thử phương pháp tiếp theo"
          
          # === PHƯƠNG PHÁP 3: Sử dụng webhook ===
          if [ $? -ne 0 ]; then
            echo "=== Triển khai với webhook ==="
            TAG="github-action-$(date +%Y%m%d%H%M%S)"
            WEBHOOK_URL="https://encore.dev/webhook/deploy/$ENCORE_AUTH_TOKEN/$APP_ID"
            echo "Gửi webhook triển khai..."
            curl -X POST "$WEBHOOK_URL" -d "branch=main&tag=$TAG" || echo "Webhook không thành công"
          fi
          
          echo "===== Quy trình triển khai hoàn tất ====="
          echo "Kiểm tra trạng thái triển khai tại: https://app.encore.cloud/$APP_ID"