name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npm run type-check
      
      - name: Debug directory structure
        run: find . -name "*.test.ts" -type f
      
      - name: Run tests
        run: npm test
  
  deploy:
    name: Deploy to Encore Cloud
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    env:
      ENCORE_AUTH: ${{ secrets.ENCORE_AUTH_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Git for Encore
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Create and deploy package to Encore Cloud
        run: |
          # Lấy App ID từ encore.app
          APP_ID=$(cat encore.app | grep id | cut -d'"' -f4)
          echo "App ID: $APP_ID"
          
          # Chuẩn bị thư mục triển khai
          DEPLOY_DIR=$(mktemp -d)
          echo "Tạo thư mục tạm: $DEPLOY_DIR"
          
          # Sao chép toàn bộ code vào thư mục triển khai
          cp -r . $DEPLOY_DIR
          cd $DEPLOY_DIR
          
          # Tạo tệp tin zip để triển khai
          DEPLOY_PACKAGE="encore_deployment.zip"
          zip -r $DEPLOY_PACKAGE *
          
          # Gửi yêu cầu API để triển khai gói
          echo "Gửi yêu cầu triển khai lên Encore Cloud..."
          curl -X POST "https://api.encore.dev/v1/apps/${APP_ID}/deploy" \
            -H "Authorization: Bearer ${{ secrets.ENCORE_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "branch": "main",
              "commit_message": "Deploy from GitHub Actions",
              "deploy_mode": "automatic"
            }'
          
          # Kiểm tra kết quả curl
          CURL_EXIT=$?
          if [ $CURL_EXIT -ne 0 ]; then
            echo "CURL failed with exit code $CURL_EXIT"
            echo "Thử phương pháp thay thế..."
            
            # Sử dụng phương pháp webhook thay thế
            WEBHOOK_URL="https://encore.dev/webhook/deploy/${{ secrets.ENCORE_AUTH_TOKEN }}/$APP_ID"
            echo "Gửi webhook triển khai..."
            curl -X POST "$WEBHOOK_URL" \
              -d "branch=main&message=Deploy from GitHub Actions"
          fi
          
          echo "===== Triển khai hoàn tất ====="
          echo "Kiểm tra trạng thái triển khai tại: https://app.encore.cloud/$APP_ID"
          
      - name: Verify deployment status
        if: always()
        run: |
          APP_ID=$(cat encore.app | grep id | cut -d'"' -f4)
          echo "Bạn có thể kiểm tra trạng thái triển khai tại: https://app.encore.cloud/$APP_ID"
          echo "Nếu triển khai không thành công, bạn có thể thử:"
          echo "1. Cập nhật ENCORE_AUTH_TOKEN trong GitHub Secrets"
          echo "2. Thủ công triển khai từ terminal sử dụng phương pháp bạn đã thành công trước đây"