name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npm run type-check
      
      - name: Debug directory structure
        run: find . -name "*.test.ts" -type f
      
      - name: Run tests
        run: npm test
  
  deploy:
    name: Deploy to Encore Cloud
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    env:
      ENCORE_AUTH: ${{ secrets.ENCORE_AUTH_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install Encore CLI
        run: |
          curl -s https://encore.dev/install.sh | bash
          echo "$HOME/.encore/bin" >> $GITHUB_PATH
      
      - name: Set up Git for Encore
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Setup Encore auth
        run: |
          mkdir -p ~/.encore
          echo "${{ secrets.ENCORE_AUTH_TOKEN }}" > ~/.encore/authtoken
          chmod 600 ~/.encore/authtoken
          cat > ~/.encore/config.json << EOF
          {
            "auth": {
              "token": "${{ secrets.ENCORE_AUTH_TOKEN }}"
            }
          }
          EOF
          chmod 600 ~/.encore/config.json
      
      - name: Deploy to Encore Cloud using Git Integration
        run: |
          encore version
          APP_ID=$(cat encore.app | grep id | cut -d'"' -f4)
          echo "App ID: $APP_ID"
          echo "Linking app with Encore Cloud..."
          encore app link $APP_ID
          echo "Cấu hình Git remote cho Encore..."
          git remote remove encore 2>/dev/null || true
          git remote add encore "encore://$APP_ID.git"
          echo "Danh sách remote:"
          git remote -v
          echo "Cấu hình SSH cho Encore..."
          mkdir -p ~/.ssh
          ssh-keyscan encore.dev >> ~/.ssh/known_hosts 2>/dev/null || true
          ssh-keyscan git.encore.dev >> ~/.ssh/known_hosts 2>/dev/null || true
          cat > ~/.ssh/config << EOF
          Host *.encore.dev encore.dev git.encore.dev
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
          EOF
          chmod 600 ~/.ssh/config
          git config --global credential.helper store
          echo "https://token:${{ secrets.ENCORE_AUTH_TOKEN }}@git.encore.dev" > ~/.git-credentials
          chmod 600 ~/.git-credentials
          export GIT_TRACE=1
          echo "Đang triển khai lên Encore Cloud..."
          git push encore HEAD:refs/heads/main -f
          echo "===== Triển khai hoàn tất ====="
          echo "Kiểm tra trạng thái triển khai tại: https://app.encore.cloud/$APP_ID"