name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npm run type-check
      
      - name: Debug directory structure
        run: find . -name "*.test.ts" -type f
      
      - name: Run tests
        run: npm test
  
  deploy:
    name: Deploy to Encore Cloud
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install Encore CLI
        run: |
          curl -s https://encore.dev/install.sh | bash
          echo "$HOME/.encore/bin" >> $GITHUB_PATH
      
      - name: Set up Git for Encore
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Authenticate and deploy to Encore Cloud
        run: |
          # Đăng nhập với API key
          encore auth login --auth-key=${{ secrets.ENCORE_AUTH_TOKEN }}
          
          # Hiển thị phiên bản Encore
          encore version
          
          # Kiểm tra app ID từ file encore.app
          APP_ID=$(cat encore.app | grep id | cut -d'"' -f4)
          echo "App ID: $APP_ID"
          
          # Thực hiện link với app trên Encore Cloud
          echo "Linking app with Encore Cloud..."
          encore app link $APP_ID
          
          # Kiểm tra git remotes để debug
          echo "Checking git remotes:"
          git remote -v
          
          # Lấy commit ID hiện tại để sử dụng làm tag
          COMMIT_ID=$(git rev-parse --short HEAD)
          IMAGE_TAG="mission-brief:$COMMIT_ID"
          
          echo "==== Đang triển khai lên Encore Cloud ===="
          
          # Kiểm tra các lệnh có sẵn
          echo "Available encore commands:"
          encore -h
          
          # Chạy lệnh check để kiểm tra ứng dụng
          encore check
          
          # Xem thông tin về lệnh run
          echo "Run command options:"
          encore run -h
          
          # Sử dụng lệnh run với flag --publish để deploy lên cloud
          echo "Deploying to Encore Cloud..."
          encore run --publish
          
          echo "Triển khai hoàn tất. Truy cập https://app.encore.cloud/$APP_ID để xem chi tiết."
        env:
          ENCORE_AUTH_TOKEN: ${{ secrets.ENCORE_AUTH_TOKEN }}