name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npm run type-check
      
      - name: Debug directory structure
        run: find . -name "*.test.ts" -type f
      
      - name: Run tests
        run: npm test
  
  deploy:
    name: Deploy to Encore Cloud
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install Encore CLI
        run: |
          curl -s https://encore.dev/install.sh | bash
          echo "$HOME/.encore/bin" >> $GITHUB_PATH
      
      - name: Set up Git for Encore
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Setup direct deployment to Encore Cloud
        run: |
          # Đăng nhập với API key
          encore auth login --auth-key=${{ secrets.ENCORE_AUTH_TOKEN }}
          
          # Kiểm tra app ID từ file encore.app
          APP_ID=$(cat encore.app | grep id | cut -d'"' -f4)
          echo "App ID: $APP_ID"
          
          # Thực hiện link với app trên Encore Cloud
          echo "Linking app with Encore Cloud..."
          encore app link $APP_ID
          
          # Kiểm tra git remotes để debug
          echo "Checking git remotes:"
          git remote -v
          
          # Chạy lệnh check để kiểm tra ứng dụng
          echo "Checking application for errors..."
          encore check
          
          echo "Preparing for deployment via API request..."
      
      - name: Deploy to Encore Cloud using curl
        run: |
          # Lấy APP_ID từ encore.app
          APP_ID=$(cat encore.app | grep id | cut -d'"' -f4)
          COMMIT_SHA=$(git rev-parse HEAD)
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          
          # Tạo JSON cho deployment request
          cat > deploy-payload.json << EOF
          {
            "commit_sha": "$COMMIT_SHA",
            "commit_branch": "$CURRENT_BRANCH",
            "commit_message": "Deploy from GitHub Actions CI/CD",
            "push_source": "github_actions"
          }
          EOF
          
          # Hiển thị payload để debug
          echo "Deployment payload:"
          cat deploy-payload.json
          
          # Gửi request tới Encore API để deploy
          echo "Sending deployment request to Encore Cloud..."
          curl -X POST "https://api.encore.dev/v1/apps/$APP_ID/deployments" \
            -H "Authorization: Bearer ${{ secrets.ENCORE_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @deploy-payload.json
          
          echo "Deployment request sent. Check status at https://app.encore.cloud/$APP_ID/deployments"
        env:
          ENCORE_AUTH_TOKEN: ${{ secrets.ENCORE_AUTH_TOKEN }}